/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author 249bh
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
       
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pizza ID ", "Pizza Name", "Size", "Veg", "Price", "Qty", "Total"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("pizza ID ");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 576, 280));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Total Amt");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 130, 40));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 74, 107, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Amt Paid");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 107, 37));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 107, 44));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Balance");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 107, 35));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 110, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Print Invoice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 190, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Cart");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 340, 470, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void sales() throws ClassNotFoundException
    {
        int lastid=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/varietydb","root","");
            String total=jTextField1.getText();
            String pay = jTextField2.getText();
            String bal = jTextField3.getText();
            //String query = "insert into sales(subtotal,pay,bal)values(?,?,?)";
            String query = "insert into `sales` (`subtotal`,`pay`,`bal`)values(?,?,?)";
            PreparedStatement pst=con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, total);
            pst.setString(2, pay);
            pst.setString(3, bal);
            pst.executeUpdate();
            ResultSet rs=pst.getGeneratedKeys();
            
            if(rs.next())
            {
                lastid = rs.getInt(1);
            }
           
            
            
            //String query1="insert into sales_product(sales_id,prodname,price,qty,total)values(?,?,?,?,?)";
            String query1="INSERT INTO `sales_product` (`sales_id`,`pizza ID`, `Pizza Name`, `Size`, `Veg`, `Price`,`Qty`,`Total`) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement pst1=con.prepareStatement(query1);

           
            String id;
            String name;
            String size;
            String veg;
            String price;
            String qty;
            String tot;
            
            
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                id=(jTable1.getValueAt(i, 0).toString());
                name=(String)jTable1.getValueAt(i,1);
                size=(String)jTable1.getValueAt(i, 2);
                veg=(String)jTable1.getValueAt(i, 3);
                price=jTable1.getValueAt(i, 4).toString();
                qty=jTable1.getValueAt(i, 5).toString();
                tot = jTable1.getValueAt(i,6).toString();
                
                
                pst1.setInt(1,lastid);
                pst1.setString(2,id);
                pst1.setString(3,name);
                pst1.setString(4,size);
                pst1.setString(5,veg);
                pst1.setString(6,price);
                pst1.setString(7, qty);
                pst1.setString(8, tot);
                pst1.executeUpdate();
            
            
            }            
           JOptionPane.showMessageDialog(this,"Sales Completed!!!");
             
          /* HashMap a=new HashMap();
           a.put("invo",lastid);
           
           
           try{
            JasperDesign jdesign=JRXmlLoader.load("C:\\Users\\249bh\\OneDrive\\Documents\\NetBeansProjects\\JavaApplication3\\src\\newpackage\\report1.jrxml");
            JasperReport jreport=JasperCompileManager.compileReport(jdesign);
            
            JasperPrint jprint=JasperFillManager.fillReport(jreport, a, con);
            
            JasperViewer.viewReport(jprint);
            
            
        }   catch (JRException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.removeRow(jTable1.getSelectedRow());
         int sum = 0;
         for(int a=0; a<jTable1.getRowCount(); a++)
        {
            
            sum = sum + Integer.parseInt(jTable1.getValueAt(a, 6).toString());
            
        }
        jTextField1.setText(Integer.toString(sum));
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame j = new NewJFrame();
        j.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int tot,payment,balance;
        
        payment = Integer.parseInt(jTextField2.getText());
        tot = Integer.parseInt(jTextField1.getText());
        balance = payment - tot;
        jTextField3.setText(String.valueOf(balance));
        
        try {
            sales();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
        }
        bill();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void bill()
    {
        String total = jTextField1.getText();
        String pay   = jTextField2.getText();
        String bal   = jTextField3.getText();
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        jTextArea1.setText(jTextArea1.getText() + "******************************************************************************************\n");
        jTextArea1.setText(jTextArea1.getText() + "                                                   Invoice                                 \n");
        jTextArea1.setText(jTextArea1.getText() + "******************************************************************************************\n");
        
        
         jTextArea1.setText(jTextArea1.getText() + "Product"+"\t"+"Size"+"\t"+"Veg"+"\t"+"Price"+"\t"+"Qty"+"\t"+"Total"+"\t");
         jTextArea1.setText(jTextArea1.getText() + "\n");
         jTextArea1.setText(jTextArea1.getText() + "\n");
          
        for(int i=0;i<model.getRowCount();i++)
        {
            String productname = model.getValueAt(i, 1).toString();
            String veg = model.getValueAt(i, 3).toString();
            String size = model.getValueAt(i, 2).toString();
            String price =  model.getValueAt(i, 4).toString();
            String qty = model.getValueAt(i, 5).toString();
            String tot = model.getValueAt(i, 6).toString();
           // String productname = (String)model.getValueAt(i, 1);
            //String productname = (String)model.getValueAt(i, 1);
            jTextArea1.setText(jTextArea1.getText() + productname +"\t"+size +"\t"+veg+"\t"+price+"\t"+qty+"\t"+ tot +"\t" );
            jTextArea1.setText(jTextArea1.getText() + "\n"); 
        }
        
        
          jTextArea1.setText(jTextArea1.getText() + "\n");  
          jTextArea1.setText(jTextArea1.getText() + "\n"); 
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"\t"+"Subtotal : " + total + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"\t"+"Payment : " + pay + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"\t"+"Balance : " + bal + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\n"); 
          
          jTextArea1.setText(jTextArea1.getText() + "*********************************************************************************************\n");
          jTextArea1.setText(jTextArea1.getText() + "                                        Thank You Come Again                                 \n");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
