/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author 249bh
 */
public class NewJFrame2 extends javax.swing.JFrame {
      
    /**
     * Creates new form NewJFrame2
     */
    ButtonGroup bg = new ButtonGroup();
    String filename = null;
    byte[] pizza_image ;
    public NewJFrame2() {
        
        initComponents();
        addgroup();
        showuser();
    }

    
                      
    private void addgroup()
    {
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        
    }
       public ArrayList<User> userList(){
        
        ArrayList<User> userList = new ArrayList<>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/varietydb","root","");
            Statement st=  con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `database`");
            User user;
            while(rs.next())
            {
                user = new User(rs.getInt("pizza ID"),rs.getString("Pizza Name"),rs.getString("Size"),rs.getString("Veg"),rs.getInt("Price"),rs.getBytes("image"));
                userList.add(user);           
            }
        }
        catch(SQLException e)
         {  
            System.out.println("error: "+ e);
         } 
         catch (ClassNotFoundException ex) {
            System.out.println("error: "+ ex);
        }
        return userList;
    }
     
    public void showuser(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0] = list.get(i).getid();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getsize();
            row[3] = list.get(i).getveg();
            row[4] = list.get(i).getprice();
            row[5] = list.get(i).getimage();
            model.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_image = new javax.swing.JLabel();
        btn_image = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("pizza id ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 62, 90, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("pizza name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, 130, 42));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("size");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 224, 73, 39));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("veg/non-veg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 331, 140, 32));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 446, 73, 36));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 55, 102, 42));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 115, 102, 42));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 99, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pizza ID", "Pizza Name", "Size", "Veg", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 40, 469, 240));

        lbl_image.setBackground(new java.awt.Color(204, 204, 204));
        lbl_image.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 233, 226));

        btn_image.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_image.setText("Choose");
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 107, 47));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 110, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 120, 40));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 446, 99, 36));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "small", "medium", "large", "ex Large" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 102, 29));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("veg");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 306, 93, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("non-Veg");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 353, 93, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 99, 43));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String id    =    jTextField1.getText();
        String name  =    jTextField2.getText();
        String size; 
        String veg=null;
        String price =    jTextField3.getText();
        
      
      
        Connection con;
        PreparedStatement insert;
        
          try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/varietydb","root","");
            insert = con.prepareStatement("INSERT INTO `database` (`pizza ID`, `Pizza Name`, `Size`, `Veg`, `Price`,`image`) VALUES (?,?,?,?,?,?)");
            
            insert.setString(1,id);
            insert.setString(2,name);
            size = jComboBox1.getSelectedItem().toString();
            insert.setString(3,size);
            if(jRadioButton1.isSelected())
            {
                veg = "veg";  
            }
            if(jRadioButton2.isSelected() )
            {
                veg = "non-Veg";    
            }
            insert.setString(4,veg);
            insert.setString(5,price);
            insert.setBytes(6,pizza_image);
            //put if statement for empty field boxes//
            insert.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            model.setRowCount(0);
            showuser();
            JOptionPane.showMessageDialog(this, "Record Saved");
            
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            buttonGroup1.clearSelection();
            jComboBox1.setSelectedIndex(0);
            
            
 
        } catch (ClassNotFoundException ex) {
            System.out.println("error: "+ ex);
        } catch (SQLException ex) {
            System.out.println("error: "+ ex);
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        NewJFrame j = new NewJFrame();
        j.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        // TODO add your handling code here:
         JFileChooser Chooser = new JFileChooser();
         Chooser.showOpenDialog(null);
         Chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         Chooser.addChoosableFileFilter(filter);
         File f = Chooser.getSelectedFile();
         filename = f.getAbsolutePath();
         int result = Chooser.showSaveDialog(null);
         ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH));
         lbl_image.setIcon(imageIcon);
         try{
             File image = new File(filename);
             FileInputStream fis = new FileInputStream(image);
             ByteArrayOutputStream bos = new ByteArrayOutputStream(); 
             byte[] buf = new byte[1024];
             for (int readNum;(readNum = fis.read(buf)) != -1;)
             {
                 bos.write(buf,0,readNum);
             }
             pizza_image = bos.toByteArray();
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(this,"image is not entered");
         }
         
    }//GEN-LAST:event_btn_imageActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        jTextField1.setText(model.getValueAt(i,0).toString());
        jTextField2.setText(model.getValueAt(i,1).toString());
        
        
         String size = model.getValueAt(i,2).toString();
                  switch(size)
                  {
                      case "small":
                         jComboBox1.setSelectedIndex(0);
                         break;
                      case "medium":
                         jComboBox1.setSelectedIndex(1);
                         break;
                      case "large":
                         jComboBox1.setSelectedIndex(2);
                         break;
                      case "ex Large":
                         jComboBox1.setSelectedIndex(3);
                         break;
                  }
          String veg = model.getValueAt(i,3).toString();
             if(veg.equals("veg"))
                     {
                         jRadioButton1.setSelected(true);
                         jRadioButton2.setSelected(false);
                     }
             else
                     {
                         jRadioButton2.setSelected(true);
                         jRadioButton1.setSelected(false);
                     }
                   
           jTextField3.setText(model.getValueAt(i,4).toString());     
               
        
        byte[] img = (userList().get(i).getimage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH));
        lbl_image.setIcon(imageIcon);
        
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
        Connection con;
        PreparedStatement insert;
        
        int opt = JOptionPane.showConfirmDialog(null,"Are You sure to Delete","Delete",JOptionPane.YES_NO_OPTION);   
        if(opt == 0){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/varietydb","root","");
            int row = jTable2.getSelectedRow();
            String value = (jTable2.getModel().getValueAt(row,0).toString());
            String query = "DELETE FROM `database`  where `database`.`pizza ID` = " + value;
            insert = con.prepareStatement(query);
            insert.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            model.setRowCount(0);
            showuser();
            JOptionPane.showMessageDialog(this, "deleted successfully");
        }
        catch (ClassNotFoundException ex) {
            System.out.println("error: "+ ex);
        } catch (SQLException ex) {
            System.out.println("error: "+ ex);
        }  
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement insert;
        String id    =    jTextField1.getText();
        String name  =    jTextField2.getText();
        String size; 
        String veg=null;
        String price =    jTextField3.getText();
        
     
      
           try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/varietydb","root","");
            int row = jTable2.getSelectedRow();
            String value = (jTable2.getModel().getValueAt(row,0).toString());
            String query = "UPDATE `database` SET `pizza ID`=?, `Pizza Name`=?,`Size`=?,`Veg`=?,`Price`=?,`image`=? WHERE `database`.`pizza ID`=" + value;
            insert = con.prepareStatement(query);
            
            insert.setString(1,id);
            insert.setString(2,name);
            size = jComboBox1.getSelectedItem().toString();
            insert.setString(3,size);
            if(jRadioButton1.isSelected())
            {
                veg = "veg";  
                jRadioButton1.setSelected(true);
                jRadioButton2.setSelected(false);
            }
            if(jRadioButton2.isSelected())
            {
                veg = "non-Veg";  
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(true);
            }
            insert.setString(4,veg);
            insert.setString(5,price);
            insert.setBytes(6,pizza_image);
            //put if statement for empty field boxes//
            
        
             
                 insert.executeUpdate();
                 DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
                 model.setRowCount(0);
                 showuser();
                 JOptionPane.showMessageDialog(this, "update successfully");
            
             
            
          }
                
          catch (ClassNotFoundException ex) {
            System.out.println("error: "+ ex);
        } catch (SQLException ex) {
            System.out.println("error: "+ ex);
        }       
          
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable2MouseEntered

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_image;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_image;
    // End of variables declaration//GEN-END:variables
}
