/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 249bh
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public NewJFrame4() {
        initComponents();
        //bill();
    }
      
    /*public void bill()
    {
        NewJFrame3 njf = new NewJFrame3();
        
        String total = njf.jTextField1.getText();
        String pay   = njf.jTextField2.getText();
        String bal   = njf.jTextField3.getText();
        
        DefaultTableModel model = (DefaultTableModel)njf.jTable1.getModel();
        
        jTextArea1.setText(jTextArea1.getText() + "********************************************************************\n");
        jTextArea1.setText(jTextArea1.getText() + "                                  Invoice                          \n");
        jTextArea1.setText(jTextArea1.getText() + "********************************************************************\n");
        
        
         jTextArea1.setText(jTextArea1.getText() + "Product"+"\t"+"Size"+"\t"+"Veg"+"\t"+"Price"+"\t"+"Qty"+"\t"+"Total"+"\t");
         jTextArea1.setText(jTextArea1.getText() + "\n");
         jTextArea1.setText(jTextArea1.getText() + "\n");
          
        for(int i=0;i<model.getRowCount();i++)
        {
            String productname = model.getValueAt(i, 1).toString();
            String veg = model.getValueAt(i, 3).toString();
            String size = model.getValueAt(i, 2).toString();
            String price =  model.getValueAt(i, 4).toString();
            String qty = model.getValueAt(i, 5).toString();
            String tot = model.getValueAt(i, 6).toString();
           // String productname = (String)model.getValueAt(i, 1);
            //String productname = (String)model.getValueAt(i, 1);
            jTextArea1.setText(jTextArea1.getText() + productname +"\t"+size +"\t"+veg+"\t"+price+"\t"+qty+"\t"+ tot +"\t" );
            jTextArea1.setText(jTextArea1.getText() + "\n"); 
        }
        
        
          jTextArea1.setText(jTextArea1.getText() + "\n");  
          jTextArea1.setText(jTextArea1.getText() + "\n"); 
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"Subtotal : " +total + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"Payment : " + pay + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\t"+"\t"+"\t"+"\t"+"Balance : " + bal + "\n");
          jTextArea1.setText(jTextArea1.getText() + "\n"); 
          
          jTextArea1.setText(jTextArea1.getText() + "*******************************************************************\n");
          jTextArea1.setText(jTextArea1.getText() + "                         Thank You Come Again                      \n");
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
